### PR TITLE
Added 'preset current configuration' with New Config utility [8]

### PR DESCRIPTION
**Pull request by bergware**

### CODE REVIEW

**Comment by limetech** [comment]
Nice feature, and I like the simplifications.  One request: please put 'none' at the top and 'all' at the bottom.  This way, if user does not change selection, the utility works the way it did before.

**Comment by bergware** [comment]
Changed from default "All" to default "None" (mimic current behavior)

**Comment by bergware** [comment]
Needed to invent some "trickery" to play nice with emhttp :)

**Comment by bergware** [comment]
hold your horses, my simplications don't work :(

looking for a solution !

**Comment by bergware** [comment]
Ok, correction made.

**Comment by limetech** [comment]
horses held... let'em loose now?

**Comment by bergware** [comment]
loosen the reins... (not sure if this an english expression)

**Comment by limetech** [comment]
In the text "Preset current configuration", perhaps change to "Retain current configuration".

**Pull request merged**
