### PR TITLE
Add dropdown menu for Categories

### PR DESCRIPTION
**Pull request by gfjardim**
Just fixed the black theme dropdown CSS.

### CODE REVIEW

**Comment by limetech** [comment]
Curious: What does RW/Shared (rw,shared) actually do, and why is this useful?

**Comment by gfjardim** [comment]
It got lost in the middle of this PR. It's only relevant to [this](https://github.com/limetech/dynamix-6.2/issues/4) issue.

**Comment by limetech** [comment]
What I'm asking is, how is it relevant?  That is, if we do the bind-mount trick on /mnt and we invoke docker with "--propagation slave", isn't that enough now for containers to see "new" mounts that occur under /mnt after the docker engine is started?  Now, what purpose does 'rw,shared' serve?  Guess I'm confused.... as usual :)

**Comment by gfjardim** [comment]
Ah, now I understand.

When docker starts, it will clone the parent namespace (let's call PN the parent namespace and CN the docker child namespace ).

Now, at first, PN and CN are equal, but when docker starts to mount volumes in CN, those targets become invisible to PN processes. This occur because, by default, all mounts are `private`. The same occur when we mount targets on PN, they are invisible to CN process.

Now, when PN makes e.g. **/mnt** shared, this directory can be shared with CN processes, but, when we map a volume in docker (CN), it will be, by default, mounted as `private`. So we have to let the daemon know that we want that specific volume to be mounted as shared or slave.

I think it should be set to `rw,slave`, because this prevents undesirable effects of **upward propagation**; in thesis, if `shared` a container could unmount a PN mount target.

**Comment by gfjardim** [comment]
I've tested it, and a `shared mount` could leave the host vulnerable to a container issued unmount, if the container is privileged. With container's volume mounted as `slave`, the unmount only took place inside the container's namespace, and the host mount was unaffected.

**Pull request merged**
